### ISSUE TITLE
SetAccountStore(string hrefOrNameKey) only works with full href

### ISSUE THREAD

**Issue by DarinMacRae** [stormpath/stormpath-sdk-dotnet#119] opened 2016-01-12 23:48 UTC
If you just give the ID of the account store it won't work as you get an error that indicates that there is no account store by that identifier. However, it does work if you give the full href. 

```
            var authRequest = new UsernamePasswordRequestBuilder()
                .SetUsernameOrEmail(usernameOrEmail)
                .SetPassword(password)
                .SetAccountStore("somevalidIDbutnotanHref") // <--- this won't work
                .Build();

```

**Comment by nbarbettini** [comment] 2016-01-12 23:52
This is by design. If the given string is not an href, it's assumed to be an Organization `nameKey`.

Is there a scenario where you have the Account Store's ID but not the full href available?

**Comment by DarinMacRae** [comment] 2016-01-13 00:12
Oh, I see now. I think perhaps it was the name of the param that threw me. "hrefOrNameKey" said to me that I could provide either the full href or just the id. I didn't understand that nameKey was something entirely different. The value is overloaded.

I understand now that you explained it. I can provide the full href but sometimes it will be an href for a directory and sometimes for an organization.

Might I suggest kindly that you consider:
```
SetAccountStore(string href)  (an href to any account store)
SetAccountStore(IAccountStore store)
SetAccountStore(INameKey nameKey) 
```
I understand the trade-offs here but it would prevent misunderstandings when string values are overloaded.

**Comment by nbarbettini** [comment] 2016-01-13 03:52
It's fine if it's sometimes a Directory href and sometimes an Organization href - as long as it's any Account Store resource (Directory, Group, or Organization) it'll take it.

Thanks for the suggestion. I'll close this issue for now but consider it as a breaking change in a future release. :+1:

**Closed by nbarbettini** 2016-01-13 03:52 UTC
Labels: question
