### ISSUE TITLE
Implement stormpath_social grant type in SDK

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-sdk-dotnet#199] opened 2016-08-11 22:56 UTC
https://docs.stormpath.com/rest/product-guide/latest/auth_n.html?highlight=stormpath_social#generating-an-oauth-2-0-access-token

**Comment by nbarbettini** [comment] 2016-08-15 22:14
Dupe of #200

**Closed as completed by nbarbettini** 2016-08-15 22:14 UTC
